### ISSUE TITLE
Doesn't work on current version

### ISSUE THREAD

**Issue by lmartins** [Emmeran/brackets-overscroll#2]
Hi,

For some reason I really like feature coming from other editors.
I've installed the extension but it doesn't do anything. Am I missing something?

Cheers

**Comment by iorippi** [comment]
@lmartins
Hi,
I had the same problem, but I've just found a fix so hope this helps.

# Possible cause?

It looks like the extension that will be installed through the 'Extension Manager' is a bit different from the one provided on GitHub: Download ZIP file.
I haven't looked at it close enough, but it seems like 'main.js' is missing the "!important" portion from the line 11th.

``` javascript
// line 10 of main.js
// instaleld manually from zip file
    AppInit.appReady(function () {
        $("<style>.CodeMirror-sizer { margin-bottom: 1000px !important }</style>").appendTo("head");
    });

// line 10 of main.js
// installed by Extension Manager
// Note that this one is missing '!important'
    AppInit.appReady(function () {
        $("<style>.CodeMirror-sizer { margin-bottom: 1000px }</style>").appendTo("head");
    });
```

Probably you can just edit this portion and it will be solved.
However, I think it's better to uninstall the whole thing and re-install manually.
I put the instruction below, so if you needed, please use this!

# Note

I'm currently using Brackets release 1.2 build 1.2.0-0 on WinVista/Win7 machines,
And so I haven't tested my solution on any kind of Macs, but I suppose it works fine.

# Instructions
1. ### Preparation -Uninstall
   
   -If you have already uninstalled the extension, skip to step 2.
   1. Choose 'File' > 'Extension Manager'
   2. Under 'Installed', find 'Overscroll',
        then choose 'uninstall'
   3. Finish uninstall by restarting Brackets.
        (Make sure you have saved files edits if there's any)
2. ### Download the extension from GitHub
   1. Go to https://github.com/Emmeran/brackets-overscroll
   2. Download Zip file from the right column's bottom, where it says "Download ZIP"
   3. Uncompress 'brackets-overscroll-master'
3. ### Open Extensions Install Location
   1. #### Choose 'Help' > 'Show Extensions Folder'
      
      You are most likely led to... 
      **[On Mac:]**  /Users/<user>/Library/Application Support/Brackets/extensions/user 
      **[On Windows:]**  C:\Users<user>\AppData\Roaming\Brackets\extensions\user 
      And you should be seeing the names of folders for each on of your extensions already installed. 
      Otherwise, if you were seeing  _'disabled'_ and _'user'_ folder, 
      then open _'user'_ folder, and now you should be able to see extension folders.  
   2. #### Make sure 1.(uninstall) had done successfully
      
        If you are not seeing folder named "brackets-overscroll", then it's okay.
        Otherwise, repeat step 1.
        _(I had found this once for somereason, but I suppose it was just my mistake..)_
4. ### Install "Overscroll" Extension
   1. Put "brackets-overscroll-master" that you have uncompressed on step 2.
        onto the folder you have just opened in step 3.
        *I renamed the folder as "brackets-overscroll" just in order to match the original. *
   2. Restart Brackets
5. ### Confirm Installation success
   1. Choose 'File' > 'Extension Manager'
   2. Under 'Installed', you should be able to find 'Overscroll'
   3. Open whatever document and it should be working now!

_fin._

---

Hope this helps!

**Comment by lmartins** [comment]
Thank you Alex
